# List of WS methods to whitelist.
ws_method_whitelist = ["starknet_chainId"]
# Enable WS on this backend group. There can only be one WS-enabled backend group.
ws_backend_group = "main"

[server]
# Host for the nori RPC server to listen on.
rpc_host = "0.0.0.0"
# Port for the above.
rpc_port = 8080
# Host for the nori WS server to listen on.
ws_host = "0.0.0.0"
# Port for the above
# Set the ws_port to 0 to disable WS
ws_port = 8085
# Maximum client body size, in bytes, that the server will accept.
max_body_size_bytes = 10485760
max_concurrent_rpcs = 1000
# Server log level
log_level = "info"

[redis]
# URL to a Redis instance.
url = "redis://localhost:6379"

[metrics]
# Whether or not to enable Prometheus metrics.
enabled = true
# Host for the Prometheus metrics endpoint to listen on.
host = "0.0.0.0"
# Port for the above.
port = 9761

[backend]
# How long nori should wait for a backend response before timing out.
response_timeout_seconds = 5
# Maximum response size, in bytes, that nori will accept from a backend.
max_response_size_bytes = 5242880
# Maximum number of times nori will try a backend before giving up.
max_retries = 3
# Number of seconds to wait before trying an unhealthy backend again.
out_of_service_seconds = 600
# Maximum latency accepted to serve requests, default 10s
max_latency_threshold = "30s"
# Maximum latency accepted to serve requests before degraded, default 5s
max_degraded_latency_threshold = "10s"
# Maximum error rate accepted to serve requests, default 0.5 (i.e. 50%)
max_error_rate_threshold = 0.3

[backends]
# A map of backends by name.
[backends.madara]
rpc_url = "http://localhost:9944"

[backends.katana]
rpc_url = "http://localhost:5050"

[backends.infura]
# The URL to contact the backend at. Will be read from the environment
# if an environment variable prefixed with $ is provided.
rpc_url = "http://localhost"
# The WS URL to contact the backend at. Will be read from the environment
# if an environment variable prefixed with $ is provided.
ws_url = ""
username = ""
# An HTTP Basic password to authenticate with the backend. Will be read from
# the environment if an environment variable prefixed with $ is provided.
password = ""
max_rps = 3
max_ws_conns = 1
# Path to a custom root CA.
ca_file = ""
# Path to a custom client cert file.
client_cert_file = ""
# Path to a custom client key file.
client_key_file = ""
# Allows backends to skip peer count checking, default false
# consensus_skip_peer_count = true

[backends.alchemy]
rpc_url = "http://localhost"
ws_url = ""
username = ""
password = ""
max_rps = 3
max_ws_conns = 1

[backend_groups]
[backend_groups.main]
backends = ["madara"]
# Enable consensus awareness for backend group, making it act as a load balancer, default false
# consensus_aware = true
# Period in which the backend wont serve requests if banned, default 5m
# consensus_ban_period = "1m"
# Maximum delay for update the backend, default 30s
# consensus_max_update_threshold = "20s"
# Maximum block lag, default 8
# consensus_max_block_lag = 16
# Minimum peer count, default 3
# consensus_min_peer_count = 4

[backend_groups.alchemy]
backends = ["alchemy"]

# If the authentication group below is in the config,
# nori will only accept authenticated requests.
[authentication]
# Mapping of auth key to alias. The alias is used to provide a human-
# readable name for the auth key in monitoring. The auth key will be
# read from the environment if an environment variable prefixed with $
# is provided. Note that you will need to quote the environment variable
# in order for it to be value TOML, e.g. "$FOO_AUTH_KEY" = "foo_alias".
# secret = "test"

# Mapping of methods to backend groups.
[rpc_method_mappings]
starknet_addDeclareTransaction = "main"
starknet_addDeployAccountTransaction = "main"
starknet_addInvokeTransaction = "main"
starknet_blockNumber = "main"
starknet_blockHashAndNumber = "main"
starknet_call = "main"
starknet_chainId = "main"
starknet_estimateFee = "main"
starknet_estimateMessageFee = "main"
starknet_getBlockTransactionCount = "main"
starknet_getBlockWithTxHashes = "main"
starknet_getBlockWithTxs = "main"
starknet_getClass = "main"
starknet_getClassAt = "main"
starknet_getClassHashAt = "main"
starknet_getEvents = "main"
starknet_getNonce = "main"
starknet_getStateUpdate = "main"
starknet_getStorageAt = "main"
starknet_getTransactionByBlockIdAndIndex = "main"
starknet_getTransactionByHash = "main"
starknet_getTransactionReceipt = "main"
starknet_getTransactionStatus = "main"
starknet_simulateTransaction = "main"
starknet_specVersion = "main"
starknet_syncing = "main"
starknet_traceBlockTransactions = "main"
starknet_traceTransaction = "main"
